name: publish

on: ["push"]
jobs:

  publish-python_lgpio-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Connect to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Contruire the python_lgpio Docker image
      run: |
        docker build -f Dockerfile.python_lgpio . --tag ghcr.io/julie-b35/python_lgpio:latest
        docker run ghcr.io/julie-b35/python_lgpio:latest
        docker push ghcr.io/julie-b35/python_lgpio:latest
